/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreatePetsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * unexpected error
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const CreatePetsResponse$inboundSchema: z.ZodType<
  CreatePetsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Error": "error",
  });
});

/** @internal */
export type CreatePetsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const CreatePetsResponse$outboundSchema: z.ZodType<
  CreatePetsResponse$Outbound,
  z.ZodTypeDef,
  CreatePetsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePetsResponse$ {
  /** @deprecated use `CreatePetsResponse$inboundSchema` instead. */
  export const inboundSchema = CreatePetsResponse$inboundSchema;
  /** @deprecated use `CreatePetsResponse$outboundSchema` instead. */
  export const outboundSchema = CreatePetsResponse$outboundSchema;
  /** @deprecated use `CreatePetsResponse$Outbound` instead. */
  export type Outbound = CreatePetsResponse$Outbound;
}
