workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore:
        inputs:
            - location: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore
targets:
    first-target:
        target: go
        source: petstore
        output: go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-code-samples
            blocking: false
    second-target:
        target: python
        source: petstore
        output: py
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-code-samples
            blocking: false
    third-target:
        target: typescript
        source: petstore
        output: ts
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/petstore-code-samples
            blocking: false
